// Mocks generated by Mockito 5.4.2 from annotations
// in wisy_image_uploader/test/src/core/repositories/photos.repository.interface_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wisy_image_uploader/src/core/model/photo.model.dart' as _i4;
import 'package:wisy_image_uploader/src/core/repositories/photos.repository.interface.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IPhotosRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPhotosRepository extends _i1.Mock implements _i2.IPhotosRepository {
  MockIPhotosRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> create(_i4.Photo? photo) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [photo],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Stream<List<_i4.Photo>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Photo>>.empty(),
      ) as _i3.Stream<List<_i4.Photo>>);
}
